In [1]:
import pandas as pd 
import numpy as np 

#ML
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from scipy import stats
import matplotlib.pyplot as plt
import os
import seaborn as sns
from tqdm import tqdm

1. be sure about models of this paper: https://www.pnas.org/doi/10.1073/pnas.2312202121 
2. need to explain precesion, recall, .... in the paper and the relation with being bias
3. needs to be in a challenging situation
4. we need to test pnas paper models 

In [4]:
network_list = ['conf', 'email_eu_modified', 'hospital', 'school', 'work']
network_name = network_list[1]

complex_data = pd.read_csv(f"../results/weighted/given_th_n=300/weighted_complex_{network_name}_EPH.csv")
simple_data = pd.read_csv(f"../results/weighted/given_betha_n=300/weighted_simple_{network_name}_EPH.csv")

#with fixed theta:
complex_data = complex_data[complex_data['theta'] == 0.2]
simple_data = simple_data.sample(len(complex_data),random_state=432)

# Extract features and labels
complex_EPH = complex_data['EPH'].values
simple_EPH = simple_data['EPH'].values

X = np.concatenate([complex_EPH, simple_EPH]).reshape(-1, 1)  # Features
y = np.concatenate([np.ones(len(complex_EPH)), np.zeros(len(simple_EPH))])  # Labels (1=complex, 0=simple)

# Shuffle data
indices = np.arange(X.shape[0])
np.random.seed(42) 
np.random.shuffle(indices)
X = X[indices]
y = y[indices]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=420)


# Train Decision Tree Classifier
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

# Evaluate the classifier
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9916666666666667

In [5]:
from sklearn.metrics import classification_report, confusion_matrix

# Evaluate the classifier's predictions
y_pred = clf.predict(X_test)

# Compute confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Compute classification report
class_report = classification_report(y_test, y_pred, target_names=['Simple (0)', 'Complex (1)'])
print("\nClassification Report:\n", class_report)


Confusion Matrix:
 [[59  1]
 [ 0 60]]

Classification Report:
               precision    recall  f1-score   support

  Simple (0)       1.00      0.98      0.99        60
 Complex (1)       0.98      1.00      0.99        60

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120



In [6]:
simple_data['betha'].mean()

0.3024

In [7]:
simple_data['betha'].unique()

array([0.5 , 0.3 , 0.4 , 0.01, 0.2 , 0.6 , 0.1 ])

In [10]:
network_list = ['conf', 'email_eu_modified', 'hospital', 'school', 'work']
network_name = network_list[1]

complex_data = pd.read_csv(f"../results/weighted/given_th_n=300/weighted_complex_{network_name}_EPH.csv")
simple_data = pd.read_csv(f"../results/weighted/given_betha_n=300/weighted_simple_{network_name}_EPH.csv")

#with fixed betha:
simple_data = simple_data[simple_data['betha']==0.6]
complex_data = complex_data.sample(len(simple_data),random_state=23)

# Extract features and labels
complex_EPH = complex_data['EPH'].values
simple_EPH = simple_data['EPH'].values

X = np.concatenate([complex_EPH, simple_EPH]).reshape(-1, 1)  # Features
y = np.concatenate([np.ones(len(complex_EPH)), np.zeros(len(simple_EPH))])  # Labels (1=complex, 0=simple)

# Shuffle data
indices = np.arange(X.shape[0])
np.random.seed(42) 
np.random.shuffle(indices)
X = X[indices]
y = y[indices]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=420)


# Train Decision Tree Classifier
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

# Evaluate the classifier
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0

In [11]:
from sklearn.metrics import classification_report, confusion_matrix

# Evaluate the classifier's predictions
y_pred = clf.predict(X_test)

# Compute confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Compute classification report
class_report = classification_report(y_test, y_pred, target_names=['Simple (0)', 'Complex (1)'])
print("\nClassification Report:\n", class_report)


Confusion Matrix:
 [[60  0]
 [ 0 60]]

Classification Report:
               precision    recall  f1-score   support

  Simple (0)       1.00      1.00      1.00        60
 Complex (1)       1.00      1.00      1.00        60

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120

